import Header from "@/components/header";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import { ThemeProvider } from "@/components/theme-provider";
import SideNav from "@/components/side-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const items = [
    { name: "ホーム", icon: "home", path: "" },
    { name: "Info", icon: "info", path: "info" },
    { name: "リソース", icon: "file-text", path: "resource" },
    { name: "リリース情報", icon: "rocket", path: "release" },
    { name: "メンバー", icon: "users", path: "member" },
    { name: "プロジェクト", icon: "gantt-chart", path: "project" },
    { name: "開発", icon: "code", path: "develop" },
    { name: "API", icon: "globe", path: "api-docs" },
    { name: "ブログ", icon: "rss", path: "blog" },
  ];

  return (
    <html lang="ja" suppressHydrationWarning={true}>
      <body className={cn(inter.className, "min-h-dvh")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <SideNav items={items}></SideNav>
          <main>{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
